[2023-01-18T00:38:42] INFO [root.showapps:67] sony_seen the whole applist
[2023-01-18T00:38:44] WARNING [django.request.log_response:241] Not Found: /apps/helo/dashboard/assets/img/ivancik.jpg
[2023-01-18T00:38:48] WARNING [django.request.log_response:241] Not Found: /css/searchicon.png
[2023-01-18T00:38:49] ERROR [django.request.log_response:241] Internal Server Error: /account/helo/js/create.js
Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\yash\billsnap\billsnapdec\accounts\views.py", line 375, in update_plan
    profile = Profile.objects.get(slug__iexact=userslug)
  File "D:\yash\billsnap\env\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
accounts.models.Profile.DoesNotExist: Profile matching query does not exist.
[2023-01-18T00:39:35] INFO [root.update_profile:325] sony_ updated profile
[2023-01-18T00:39:35] ERROR [django.request.log_response:241] Internal Server Error: /account/helo/js/create.js
Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\yash\billsnap\billsnapdec\accounts\views.py", line 375, in update_plan
    profile = Profile.objects.get(slug__iexact=userslug)
  File "D:\yash\billsnap\env\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
accounts.models.Profile.DoesNotExist: Profile matching query does not exist.
[2023-01-18T00:39:58] ERROR [django.request.log_response:241] Internal Server Error: /account/helo/js/create.js
Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\yash\billsnap\billsnapdec\accounts\views.py", line 375, in update_plan
    profile = Profile.objects.get(slug__iexact=userslug)
  File "D:\yash\billsnap\env\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
accounts.models.Profile.DoesNotExist: Profile matching query does not exist.
[2023-01-18T00:40:11] DEBUG [PIL.TiffImagePlugin.load:842] tag: YResolution (283) - type: rational (5) Tag Location: 22 - Data Location: 146 - value: b'\x00\x00\x00H\x00\x00\x00\x01'
[2023-01-18T00:40:11] DEBUG [PIL.TiffImagePlugin.load:842] tag: XResolution (282) - type: rational (5) Tag Location: 34 - Data Location: 154 - value: b'\x00\x00\x00H\x00\x00\x00\x01'
[2023-01-18T00:40:11] DEBUG [PIL.TiffImagePlugin.load:842] tag: ImageWidth (256) - type: long (4) - value: b'\x00\x00\x0b\xb8'
[2023-01-18T00:40:11] DEBUG [PIL.TiffImagePlugin.load:842] tag: Model (272) - type: string (2) Tag Location: 58 - Data Location: 162 - value: b'AC2001\x00'
[2023-01-18T00:40:11] DEBUG [PIL.TiffImagePlugin.load:842] tag: ImageLength (257) - type: long (4) - value: b'\x00\x00\x0f\xa0'
[2023-01-18T00:40:11] DEBUG [PIL.TiffImagePlugin.load:842] tag: Make (271) - type: string (2) Tag Location: 82 - Data Location: 169 - value: b'OnePlus\x00'
[2023-01-18T00:40:11] DEBUG [PIL.TiffImagePlugin.load:842] tag: YCbCrPositioning (531) - type: short (3) - value: b'\x00\x01'
[2023-01-18T00:40:11] DEBUG [PIL.TiffImagePlugin.load:842] tag: ExifIFD (34665) - type: long (4) - value: b'\x00\x00\x00\xc5'
[2023-01-18T00:40:11] DEBUG [PIL.TiffImagePlugin.load:842] tag: ResolutionUnit (296) - type: short (3) - value: b'\x00\x02'
[2023-01-18T00:40:11] DEBUG [PIL.TiffImagePlugin.load:842] tag: Orientation (274) - type: short (3) - value: b'\x00\x00'
[2023-01-18T00:40:11] DEBUG [PIL.TiffImagePlugin.load:842] tag: DateTime (306) - type: string (2) Tag Location: 142 - Data Location: 177 - value: b'2023:01:14 08:35:06\x00'
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:369] Importing BlpImagePlugin
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:369] Importing BmpImagePlugin
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:369] Importing BufrStubImagePlugin
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:369] Importing CurImagePlugin
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:369] Importing DcxImagePlugin
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:369] Importing DdsImagePlugin
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:369] Importing EpsImagePlugin
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:369] Importing FitsImagePlugin
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:369] Importing FitsStubImagePlugin
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:369] Importing FliImagePlugin
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:369] Importing FpxImagePlugin
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:372] Image: failed to import FpxImagePlugin: No module named 'olefile'
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:369] Importing FtexImagePlugin
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:369] Importing GbrImagePlugin
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:369] Importing GifImagePlugin
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:369] Importing GribStubImagePlugin
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:369] Importing Hdf5StubImagePlugin
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:369] Importing IcnsImagePlugin
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:369] Importing IcoImagePlugin
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:369] Importing ImImagePlugin
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:369] Importing ImtImagePlugin
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:369] Importing IptcImagePlugin
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:369] Importing JpegImagePlugin
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:369] Importing Jpeg2KImagePlugin
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:369] Importing McIdasImagePlugin
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:369] Importing MicImagePlugin
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:372] Image: failed to import MicImagePlugin: No module named 'olefile'
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:369] Importing MpegImagePlugin
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:369] Importing MpoImagePlugin
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:369] Importing MspImagePlugin
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:369] Importing PalmImagePlugin
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:369] Importing PcdImagePlugin
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:369] Importing PcxImagePlugin
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:369] Importing PdfImagePlugin
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:369] Importing PixarImagePlugin
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:369] Importing PngImagePlugin
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:369] Importing PpmImagePlugin
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:369] Importing PsdImagePlugin
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:369] Importing SgiImagePlugin
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:369] Importing SpiderImagePlugin
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:369] Importing SunImagePlugin
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:369] Importing TgaImagePlugin
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:369] Importing TiffImagePlugin
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:369] Importing WebPImagePlugin
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:369] Importing WmfImagePlugin
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:369] Importing XbmImagePlugin
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:369] Importing XpmImagePlugin
[2023-01-18T00:40:11] DEBUG [PIL.Image.init:369] Importing XVThumbImagePlugin
[2023-01-18T00:40:11] ERROR [django.request.log_response:241] Internal Server Error: /account/helo/sony
Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\yash\billsnap\env\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\yash\billsnap\env\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'update-plan' with keyword arguments '{'slug': 'helo', 'userslug': 'sony', 'planslug': ''}' not found. 1 pattern(s) tried: ['account/(?P<slug>[^/]+)/(?P<userslug>[^/]+)/(?P<planslug>[^/]+)\\Z']
[2023-01-18T00:41:08] ERROR [django.request.log_response:241] Internal Server Error: /account/helo/js/create.js
Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\yash\billsnap\billsnapdec\accounts\views.py", line 375, in update_plan
    profile = Profile.objects.get(slug__iexact=userslug)
  File "D:\yash\billsnap\env\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
accounts.models.Profile.DoesNotExist: Profile matching query does not exist.
[2023-01-18T00:41:14] WARNING [django.request.log_response:241] Not Found: /apps/helo/dashboard/assets/img/ivancik.jpg
[2023-01-18T00:41:31] INFO [root.editapp:92] sony_edited an app
[2023-01-18T00:41:51] WARNING [django.request.log_response:241] Not Found: /css/searchicon.png
[2023-01-18T00:43:10] ERROR [django.request.log_response:241] Internal Server Error: /plans/plan/helo/eAyXuhwiGE
Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\yash\billsnap\billsnapdec\plans\views.py", line 88, in show_plan
    return render(request, 'plans-panel/plan.html', payload)
  File "D:\yash\billsnap\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'update-plan' with keyword arguments '{'profileslug': 'yaswanth', 'planslug': ''}' not found. 1 pattern(s) tried: ['plans/update\\-plan/(?P<profileslug>[^/]+)/(?P<planslug>[^/]+)/\\Z']
