[2022-12-29T16:54:53] INFO [root.showapps:67] yaswanth_seen the whole applist
[2022-12-29T16:54:56] WARNING [django.request.log_response:241] Not Found: /apps/just/dashboard/assets/img/ivancik.jpg
[2022-12-29T16:54:59] WARNING [django.request.log_response:241] Not Found: /css/searchicon.png
[2022-12-29T16:55:00] WARNING [django.request.log_response:241] Not Found: /account/yaswanth/js/create.js
[2022-12-29T16:58:47] WARNING [django.request.log_response:241] Not Found: /account/yaswanth/js/create.js
[2022-12-29T16:58:50] WARNING [django.request.log_response:241] Not Found: /account/yaswanth/js/create.js
[2022-12-29T16:58:53] WARNING [django.request.log_response:241] Not Found: /account/yaswanth/js/create.js
[2022-12-29T16:59:27] WARNING [django.request.log_response:241] Not Found: /account/yaswanth/js/create.js
[2022-12-29T16:59:40] WARNING [django.request.log_response:241] Not Found: /account/yaswanth/js/create.js
[2022-12-29T17:00:31] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/urls.py changed, reloading.
[2022-12-29T17:00:34] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/urls.py changed, reloading.
[2022-12-29T17:00:36] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/urls.py changed, reloading.
[2022-12-29T17:00:54] ERROR [django.request.log_response:241] Internal Server Error: /account/yaswanth/just
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/views/generic/base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/views/generic/detail.py", line 109, in get
    context = self.get_context_data(object=self.object)
  File "/home/yaswanth/projects/billsnapdec/accounts/views.py", line 306, in get_context_data
    context['form'] = UpdateProfilePlanForm(appslug=self.kwargs['appslug'], profile=page_profile)
KeyError: 'appslug'
[2022-12-29T17:01:47] WARNING [django.request.log_response:241] Not Found: /css/searchicon.png
[2022-12-29T17:01:48] WARNING [django.request.log_response:241] Not Found: /account/just/yaswanth
[2022-12-29T17:02:30] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:02:39] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:02:45] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:02:50] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:02:55] WARNING [django.request.log_response:241] Not Found: /account/just/yaswanth
[2022-12-29T17:02:55] WARNING [django.request.log_response:241] Not Found: /account/just/yaswanth
[2022-12-29T17:02:56] WARNING [django.request.log_response:241] Not Found: /account/just/yaswanth
[2022-12-29T17:02:56] WARNING [django.request.log_response:241] Not Found: /account/just/yaswanth
[2022-12-29T17:02:57] WARNING [django.request.log_response:241] Not Found: /account/just/yaswanth
[2022-12-29T17:02:57] WARNING [django.request.log_response:241] Not Found: /account/just/yaswanth
[2022-12-29T17:03:03] WARNING [django.request.log_response:241] Not Found: /account/just/yaswanth
[2022-12-29T17:04:29] WARNING [django.request.log_response:241] Not Found: /account/just/yaswanth
[2022-12-29T17:04:30] WARNING [django.request.log_response:241] Not Found: /account/just/yaswanth
[2022-12-29T17:04:30] WARNING [django.request.log_response:241] Not Found: /account/just/yaswanth
[2022-12-29T17:04:30] WARNING [django.request.log_response:241] Not Found: /account/just/yaswanth
[2022-12-29T17:04:30] WARNING [django.request.log_response:241] Not Found: /account/just/yaswanth
[2022-12-29T17:04:30] WARNING [django.request.log_response:241] Not Found: /account/just/yaswanth
[2022-12-29T17:04:31] WARNING [django.request.log_response:241] Not Found: /account/just/yaswanth
[2022-12-29T17:04:31] WARNING [django.request.log_response:241] Not Found: /account/just/yaswanth
[2022-12-29T17:04:31] WARNING [django.request.log_response:241] Not Found: /account/just/yaswanth
[2022-12-29T17:04:32] WARNING [django.request.log_response:241] Not Found: /account/just/yaswanth
[2022-12-29T17:04:33] WARNING [django.request.log_response:241] Not Found: /account/just/yaswanth
[2022-12-29T17:04:37] WARNING [django.request.log_response:241] Not Found: /account/just/yaswanth
[2022-12-29T17:12:48] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:12:53] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:13:24] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:13:28] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:13:32] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:13:34] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:13:46] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:13:54] WARNING [django.request.log_response:241] Not Found: /account/just/js/create.js
[2022-12-29T17:14:04] WARNING [django.request.log_response:241] Not Found: /account/just/js/create.js
[2022-12-29T17:15:12] ERROR [django.request.log_response:241] Internal Server Error: /account/just/yaswanth
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/backends/django.py", line 62, in render
    return self.template.render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/loader_tags.py", line 208, in render
    return template.render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 177, in render
    return self._render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'dashboard' with arguments '('',)' not found. 1 pattern(s) tried: ['apps/(?P<slug>[^/]+)/dashboard/\\Z']
[2022-12-29T17:15:14] ERROR [django.request.log_response:241] Internal Server Error: /account/just/yaswanth
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/backends/django.py", line 62, in render
    return self.template.render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/loader_tags.py", line 208, in render
    return template.render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 177, in render
    return self._render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'dashboard' with arguments '('',)' not found. 1 pattern(s) tried: ['apps/(?P<slug>[^/]+)/dashboard/\\Z']
[2022-12-29T17:15:40] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:15:44] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:15:51] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:15:54] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:15:56] ERROR [django.request.log_response:241] Internal Server Error: /account/just/yaswanth
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/backends/django.py", line 62, in render
    return self.template.render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'update-profile' with arguments '('yaswanth', '')' not found. 1 pattern(s) tried: ['account/(?P<slug>[^/]+)/edit/(?P<appslug>[^/]+)\\Z']
[2022-12-29T17:16:28] WARNING [django.request.log_response:241] Not Found: /account/just/js/create.js
[2022-12-29T17:25:21] WARNING [django.request.log_response:241] Not Found: /account/just/js/create.js
[2022-12-29T17:29:23] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/urls.py changed, reloading.
[2022-12-29T17:29:31] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/urls.py changed, reloading.
[2022-12-29T17:29:43] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:29:57] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:30:28] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:30:31] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:30:36] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:31:05] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:31:11] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:31:16] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:31:19] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:32:03] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:38:32] ERROR [django.request.log_response:241] Internal Server Error: /account/just/yaswanth
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 484, in parse
    raise self.error(token, e)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 482, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ' 'accounts:update-profile' slug=slug userslug=userslug' from 'url 'accounts:update-profile' slug=slug userslug=userslug'
[2022-12-29T17:39:09] ERROR [django.request.log_response:241] Internal Server Error: /account/just/yaswanth
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/backends/django.py", line 62, in render
    return self.template.render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'update-profile' with keyword arguments '{'slug': 'just', 'userslug': ''}' not found. 1 pattern(s) tried: ['account/(?P<slug>[^/]+)/edit/(?P<userslug>[^/]+)\\Z']
[2022-12-29T17:40:10] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:40:13] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:40:16] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:40:18] WARNING [django.request.log_response:241] Not Found: /account/just/js/create.js
[2022-12-29T17:52:55] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:55:40] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:55:43] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:55:46] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:56:00] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:56:05] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:56:10] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:56:15] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:56:26] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:56:31] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:56:36] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:56:42] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:56:48] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:57:56] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:58:01] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:58:06] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:58:11] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:58:18] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:58:23] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:58:28] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:58:32] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:58:43] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:58:48] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:58:54] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:59:03] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:59:06] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:59:12] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:59:18] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:59:30] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:59:33] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:59:39] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T17:59:41] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:00:05] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:04:41] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:04:46] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:04:52] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:04:57] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:05:00] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:05:04] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:05:10] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:05:19] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:05:26] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:05:49] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:06:36] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:06:44] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:06:51] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:06:58] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:07:03] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:07:10] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:07:23] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:07:37] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:07:50] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:08:01] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:09:13] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:09:23] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:09:35] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:09:47] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:09:57] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:10:09] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:10:13] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:10:28] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:10:37] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:10:45] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:10:48] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:10:59] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:11:12] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:11:25] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:11:41] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:11:56] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:12:51] WARNING [django.request.log_response:241] Not Found: /account/just/js/create.js
[2022-12-29T18:13:35] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:13:43] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:13:52] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:14:04] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:14:15] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:14:24] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:14:32] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:14:44] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:14:53] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:20:48] WARNING [django.request.log_response:241] Not Found: /account/just/js/create.js
[2022-12-29T18:26:27] WARNING [django.request.log_response:241] Not Found: /account/just/js/create.js
[2022-12-29T18:27:07] WARNING [django.request.log_response:241] Not Found: /account/just/js/create.js
[2022-12-29T18:27:17] WARNING [django.request.log_response:241] Not Found: /account/just/js/create.js
[2022-12-29T18:33:36] WARNING [django.request.log_response:241] Not Found: /account/just/js/create.js
[2022-12-29T18:34:58] WARNING [django.request.log_response:241] Not Found: /account/just/js/create.js
[2022-12-29T18:36:03] WARNING [django.request.log_response:241] Not Found: /account/just/js/create.js
[2022-12-29T18:37:14] WARNING [django.request.log_response:241] Not Found: /account/just/js/create.js
[2022-12-29T18:40:02] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:40:06] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:40:22] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:40:54] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:41:00] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:43:21] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:43:25] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:43:33] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:43:37] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:43:59] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:44:01] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:44:06] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:44:17] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:44:20] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:44:23] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:44:24] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:44:36] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:44:46] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:45:00] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:45:05] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:45:07] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:45:11] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:45:19] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:47:57] ERROR [django.request.log_response:241] Internal Server Error: /account/just/yaswanth
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/views/generic/base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/views/generic/detail.py", line 109, in get
    context = self.get_context_data(object=self.object)
  File "/home/yaswanth/projects/billsnapdec/accounts/views.py", line 352, in get_context_data
    context['plans'] = self.kwargs['plans']
KeyError: 'plans'
[2022-12-29T18:48:24] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:48:26] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:48:28] WARNING [django.request.log_response:241] Not Found: /account/just/js/create.js
[2022-12-29T18:56:07] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:57:53] WARNING [django.request.log_response:241] Not Found: /css/searchicon.png
[2022-12-29T18:57:55] ERROR [django.request.log_response:241] Internal Server Error: /account/just/yaswanth
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/views/generic/base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/views/generic/detail.py", line 109, in get
    context = self.get_context_data(object=self.object)
  File "/home/yaswanth/projects/billsnapdec/accounts/views.py", line 345, in get_context_data
    context['form'] = UpdateUserPlanForm(appslug=self.kwargs['slug'], profile=page_profile)
  File "/home/yaswanth/projects/billsnapdec/plans/forms.py", line 31, in __init__
    super(UpdateUserPlanForm, self).__init__(*args, **kwargs)
TypeError: BaseForm.__init__() got an unexpected keyword argument 'profile'
[2022-12-29T18:58:23] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:58:27] WARNING [django.request.log_response:241] Not Found: /account/just/js/create.js
[2022-12-29T18:59:20] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T18:59:25] WARNING [django.request.log_response:241] Not Found: /account/just/js/create.js
[2022-12-29T18:59:25] WARNING [django.request.log_response:241] Not Found: /account/just/js/create.js
[2022-12-29T19:00:42] WARNING [django.request.log_response:241] Not Found: /account/just/js/create.js
[2022-12-29T19:00:43] WARNING [django.request.log_response:241] Not Found: /account/just/js/create.js
[2022-12-29T19:01:28] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T19:01:39] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T19:01:44] WARNING [django.request.log_response:241] Not Found: /account/just/js/create.js
[2022-12-29T19:01:56] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T19:03:28] ERROR [django.request.log_response:241] Internal Server Error: /account/just/yaswanth
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/backends/django.py", line 62, in render
    return self.template.render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'update-plan' with keyword arguments '{'profileslug': '', 'planslug': 'sjqHFcUaT8'}' not found. 1 pattern(s) tried: ['plans/update\\-plan/(?P<profileslug>[^/]+)/(?P<planslug>[^/]+)/\\Z']
[2022-12-29T19:04:06] WARNING [django.request.log_response:241] Not Found: /account/just/js/create.js
[2022-12-29T19:05:44] WARNING [django.request.log_response:241] Not Found: /account/just/js/create.js
[2022-12-29T19:08:19] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T19:08:25] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T19:08:31] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T19:13:09] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T19:15:23] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T19:15:32] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T19:15:36] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T19:15:43] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T19:15:46] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T19:16:08] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T19:19:24] ERROR [django.request.log_response:241] Internal Server Error: /account/just/yaswanth
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/backends/django.py", line 62, in render
    return self.template.render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'update-plan' with keyword arguments '{'slug': 'just', 'userslug': 'yaswanth', 'planslug': 'sjqHFcUaT8'}' not found. 1 pattern(s) tried: ['plans/update\\-plan/(?P<profileslug>[^/]+)/(?P<planslug>[^/]+)/\\Z']
[2022-12-29T19:19:25] ERROR [django.request.log_response:241] Internal Server Error: /account/just/yaswanth
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/backends/django.py", line 62, in render
    return self.template.render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'update-plan' with keyword arguments '{'slug': 'just', 'userslug': 'yaswanth', 'planslug': 'sjqHFcUaT8'}' not found. 1 pattern(s) tried: ['plans/update\\-plan/(?P<profileslug>[^/]+)/(?P<planslug>[^/]+)/\\Z']
[2022-12-29T19:20:05] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/urls.py changed, reloading.
[2022-12-29T19:20:12] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/urls.py changed, reloading.
[2022-12-29T19:20:20] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/urls.py changed, reloading.
[2022-12-29T19:20:26] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/urls.py changed, reloading.
[2022-12-29T19:20:29] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/urls.py changed, reloading.
[2022-12-29T19:20:38] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/urls.py changed, reloading.
[2022-12-29T19:20:50] ERROR [django.request.log_response:241] Internal Server Error: /account/just/js/create.js
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yaswanth/projects/billsnapdec/accounts/views.py", line 373, in update_plan
    profile = Profile.objects.get(slug__iexact=userslug)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
accounts.models.Profile.DoesNotExist: Profile matching query does not exist.
[2022-12-29T19:20:58] ERROR [django.request.log_response:241] Internal Server Error: /account/just/yaswanth/sjqHFcUaT8
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yaswanth/projects/billsnapdec/accounts/views.py", line 382, in update_plan
    return redirect('show_profile', slug=slug, userslug=userslug)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/shortcuts.py", line 48, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/shortcuts.py", line 145, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'show_profile' not found. 'show_profile' is not a valid view function or pattern name.
[2022-12-29T19:21:17] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T19:21:23] ERROR [django.request.log_response:241] Internal Server Error: /account/just/yaswanth/sjqHFcUaT8
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yaswanth/projects/billsnapdec/accounts/views.py", line 382, in update_plan
    return redirect('accounts:show_profile', slug=slug, userslug=userslug)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/shortcuts.py", line 48, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/shortcuts.py", line 145, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'show_profile' not found. 'show_profile' is not a valid view function or pattern name.
[2022-12-29T19:21:34] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T19:21:38] ERROR [django.request.log_response:241] Internal Server Error: /account/just/js/create.js
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yaswanth/projects/billsnapdec/accounts/views.py", line 373, in update_plan
    profile = Profile.objects.get(slug__iexact=userslug)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
accounts.models.Profile.DoesNotExist: Profile matching query does not exist.
[2022-12-29T19:21:52] ERROR [django.request.log_response:241] Internal Server Error: /account/just/js/create.js
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yaswanth/projects/billsnapdec/accounts/views.py", line 373, in update_plan
    profile = Profile.objects.get(slug__iexact=userslug)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
accounts.models.Profile.DoesNotExist: Profile matching query does not exist.
[2022-12-29T19:24:45] ERROR [django.request.log_response:241] Internal Server Error: /account/just/yaswanth
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: "'csrf_token'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 152: ''csrf_token''. Did you forget to register or load this tag?
[2022-12-29T19:25:29] ERROR [django.request.log_response:241] Internal Server Error: /account/just/js/create.js
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yaswanth/projects/billsnapdec/accounts/views.py", line 373, in update_plan
    profile = Profile.objects.get(slug__iexact=userslug)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
accounts.models.Profile.DoesNotExist: Profile matching query does not exist.
[2022-12-29T19:29:40] ERROR [django.request.log_response:241] Internal Server Error: /account/just/js/create.js
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yaswanth/projects/billsnapdec/accounts/views.py", line 373, in update_plan
    profile = Profile.objects.get(slug__iexact=userslug)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
accounts.models.Profile.DoesNotExist: Profile matching query does not exist.
[2022-12-29T19:29:48] INFO [root.update_profile:325] yaswanth_ updated profile
[2022-12-29T19:29:49] ERROR [django.request.log_response:241] Internal Server Error: /account/just/js/create.js
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yaswanth/projects/billsnapdec/accounts/views.py", line 373, in update_plan
    profile = Profile.objects.get(slug__iexact=userslug)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
accounts.models.Profile.DoesNotExist: Profile matching query does not exist.
[2022-12-29T19:30:26] INFO [root.update_profile:325] yaswanth_ updated profile
[2022-12-29T19:30:26] ERROR [django.request.log_response:241] Internal Server Error: /account/just/js/create.js
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yaswanth/projects/billsnapdec/accounts/views.py", line 373, in update_plan
    profile = Profile.objects.get(slug__iexact=userslug)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
accounts.models.Profile.DoesNotExist: Profile matching query does not exist.
[2022-12-29T19:31:48] ERROR [django.request.log_response:241] Internal Server Error: /account/just/js/create.js
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yaswanth/projects/billsnapdec/accounts/views.py", line 373, in update_plan
    profile = Profile.objects.get(slug__iexact=userslug)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
accounts.models.Profile.DoesNotExist: Profile matching query does not exist.
[2022-12-29T19:32:49] ERROR [django.request.log_response:241] Internal Server Error: /account/just/js/create.js
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yaswanth/projects/billsnapdec/accounts/views.py", line 373, in update_plan
    profile = Profile.objects.get(slug__iexact=userslug)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
accounts.models.Profile.DoesNotExist: Profile matching query does not exist.
[2022-12-29T19:33:27] ERROR [django.request.log_response:241] Internal Server Error: /account/just/js/create.js
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yaswanth/projects/billsnapdec/accounts/views.py", line 373, in update_plan
    profile = Profile.objects.get(slug__iexact=userslug)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
accounts.models.Profile.DoesNotExist: Profile matching query does not exist.
[2022-12-29T19:33:38] ERROR [django.request.log_response:241] Internal Server Error: /account/just/js/create.js
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yaswanth/projects/billsnapdec/accounts/views.py", line 373, in update_plan
    profile = Profile.objects.get(slug__iexact=userslug)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
accounts.models.Profile.DoesNotExist: Profile matching query does not exist.
[2022-12-29T19:36:35] ERROR [django.request.log_response:241] Internal Server Error: /account/just/js/create.js
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yaswanth/projects/billsnapdec/accounts/views.py", line 373, in update_plan
    profile = Profile.objects.get(slug__iexact=userslug)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
accounts.models.Profile.DoesNotExist: Profile matching query does not exist.
[2022-12-29T19:36:45] INFO [root.update_profile:325] yaswanth_ updated profile
[2022-12-29T19:36:46] ERROR [django.request.log_response:241] Internal Server Error: /account/just/js/create.js
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yaswanth/projects/billsnapdec/accounts/views.py", line 373, in update_plan
    profile = Profile.objects.get(slug__iexact=userslug)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
accounts.models.Profile.DoesNotExist: Profile matching query does not exist.
[2022-12-29T19:37:55] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T19:39:07] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T19:44:48] ERROR [django.request.log_response:241] Internal Server Error: /account/just/js/create.js
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yaswanth/projects/billsnapdec/accounts/views.py", line 373, in update_plan
    profile = Profile.objects.get(slug__iexact=userslug)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
accounts.models.Profile.DoesNotExist: Profile matching query does not exist.
[2022-12-29T19:44:49] ERROR [django.request.log_response:241] Internal Server Error: /account/just/js/create.js
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yaswanth/projects/billsnapdec/accounts/views.py", line 373, in update_plan
    profile = Profile.objects.get(slug__iexact=userslug)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
accounts.models.Profile.DoesNotExist: Profile matching query does not exist.
[2022-12-29T19:45:56] ERROR [django.request.log_response:241] Internal Server Error: /account/just/js/create.js
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yaswanth/projects/billsnapdec/accounts/views.py", line 373, in update_plan
    profile = Profile.objects.get(slug__iexact=userslug)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
accounts.models.Profile.DoesNotExist: Profile matching query does not exist.
[2022-12-29T19:48:53] ERROR [django.request.log_response:241] Internal Server Error: /account/just/js/create.js
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yaswanth/projects/billsnapdec/accounts/views.py", line 373, in update_plan
    profile = Profile.objects.get(slug__iexact=userslug)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
accounts.models.Profile.DoesNotExist: Profile matching query does not exist.
[2022-12-29T19:51:14] ERROR [django.request.log_response:241] Internal Server Error: /account/just/js/create.js
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yaswanth/projects/billsnapdec/accounts/views.py", line 373, in update_plan
    profile = Profile.objects.get(slug__iexact=userslug)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
accounts.models.Profile.DoesNotExist: Profile matching query does not exist.
[2022-12-29T19:53:22] ERROR [django.request.log_response:241] Internal Server Error: /account/just/yaswanth
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/backends/django.py", line 62, in render
    return self.template.render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'create-notification' not found. 'create-notification' is not a valid view function or pattern name.
[2022-12-29T19:53:23] ERROR [django.request.log_response:241] Internal Server Error: /account/just/yaswanth
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/backends/django.py", line 62, in render
    return self.template.render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'create-notification' not found. 'create-notification' is not a valid view function or pattern name.
[2022-12-29T19:53:32] ERROR [django.request.log_response:241] Internal Server Error: /account/just/yaswanth
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/backends/django.py", line 62, in render
    return self.template.render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/template/defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'create-notification' not found. 'create-notification' is not a valid view function or pattern name.
[2022-12-29T19:53:33] ERROR [django.request.log_response:241] Internal Server Error: /account/just/js/create.js
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yaswanth/projects/billsnapdec/accounts/views.py", line 373, in update_plan
    profile = Profile.objects.get(slug__iexact=userslug)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
accounts.models.Profile.DoesNotExist: Profile matching query does not exist.
[2022-12-29T19:53:33] ERROR [django.request.log_response:241] Internal Server Error: /account/just/js/create.js
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yaswanth/projects/billsnapdec/accounts/views.py", line 373, in update_plan
    profile = Profile.objects.get(slug__iexact=userslug)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
accounts.models.Profile.DoesNotExist: Profile matching query does not exist.
[2022-12-29T19:53:50] ERROR [django.request.log_response:241] Internal Server Error: /account/create-notification/just/
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yaswanth/projects/billsnapdec/accounts/views.py", line 370, in create_notification
    return redirect('accounts:show_profile', userslug=profile.slug, slug=slug)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/shortcuts.py", line 48, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/shortcuts.py", line 145, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'show_profile' not found. 'show_profile' is not a valid view function or pattern name.
[2022-12-29T19:54:10] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T19:54:13] ERROR [django.request.log_response:241] Internal Server Error: /account/just/js/create.js
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yaswanth/projects/billsnapdec/accounts/views.py", line 373, in update_plan
    profile = Profile.objects.get(slug__iexact=userslug)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
accounts.models.Profile.DoesNotExist: Profile matching query does not exist.
[2022-12-29T19:54:58] ERROR [django.request.log_response:241] Internal Server Error: /account/just/js/create.js
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yaswanth/projects/billsnapdec/accounts/views.py", line 373, in update_plan
    profile = Profile.objects.get(slug__iexact=userslug)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
accounts.models.Profile.DoesNotExist: Profile matching query does not exist.
[2022-12-29T19:55:17] DEBUG [PIL.PngImagePlugin.call:201] STREAM b'IHDR' 16 13
[2022-12-29T19:55:17] DEBUG [PIL.PngImagePlugin.call:201] STREAM b'PLTE' 41 306
[2022-12-29T19:55:17] DEBUG [PIL.PngImagePlugin.call:201] STREAM b'IDAT' 359 5770
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:369] Importing BlpImagePlugin
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:369] Importing BmpImagePlugin
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:369] Importing BufrStubImagePlugin
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:369] Importing CurImagePlugin
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:369] Importing DcxImagePlugin
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:369] Importing DdsImagePlugin
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:369] Importing EpsImagePlugin
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:369] Importing FitsImagePlugin
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:369] Importing FitsStubImagePlugin
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:369] Importing FliImagePlugin
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:369] Importing FpxImagePlugin
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:372] Image: failed to import FpxImagePlugin: No module named 'olefile'
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:369] Importing FtexImagePlugin
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:369] Importing GbrImagePlugin
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:369] Importing GifImagePlugin
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:369] Importing GribStubImagePlugin
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:369] Importing Hdf5StubImagePlugin
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:369] Importing IcnsImagePlugin
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:369] Importing IcoImagePlugin
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:369] Importing ImImagePlugin
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:369] Importing ImtImagePlugin
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:369] Importing IptcImagePlugin
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:369] Importing JpegImagePlugin
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:369] Importing Jpeg2KImagePlugin
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:369] Importing McIdasImagePlugin
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:369] Importing MicImagePlugin
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:372] Image: failed to import MicImagePlugin: No module named 'olefile'
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:369] Importing MpegImagePlugin
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:369] Importing MpoImagePlugin
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:369] Importing MspImagePlugin
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:369] Importing PalmImagePlugin
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:369] Importing PcdImagePlugin
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:369] Importing PcxImagePlugin
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:369] Importing PdfImagePlugin
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:369] Importing PixarImagePlugin
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:369] Importing PngImagePlugin
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:369] Importing PpmImagePlugin
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:369] Importing PsdImagePlugin
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:369] Importing SgiImagePlugin
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:369] Importing SpiderImagePlugin
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:369] Importing SunImagePlugin
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:369] Importing TgaImagePlugin
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:369] Importing TiffImagePlugin
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:369] Importing WebPImagePlugin
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:369] Importing WmfImagePlugin
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:369] Importing XbmImagePlugin
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:369] Importing XpmImagePlugin
[2022-12-29T19:55:17] DEBUG [PIL.Image.init:369] Importing XVThumbImagePlugin
[2022-12-29T19:55:18] ERROR [django.request.log_response:241] Internal Server Error: /account/just/js/create.js
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yaswanth/projects/billsnapdec/accounts/views.py", line 373, in update_plan
    profile = Profile.objects.get(slug__iexact=userslug)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
accounts.models.Profile.DoesNotExist: Profile matching query does not exist.
[2022-12-29T20:11:10] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T20:11:14] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T20:11:17] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T20:11:22] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T20:11:28] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T20:11:31] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T20:11:35] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T20:12:05] ERROR [django.request.log_response:241] Internal Server Error: /account/just/js/create.js
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yaswanth/projects/billsnapdec/accounts/views.py", line 373, in update_plan
    profile = Profile.objects.get(slug__iexact=userslug)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
accounts.models.Profile.DoesNotExist: Profile matching query does not exist.
[2022-12-29T20:12:44] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T20:12:46] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T20:12:54] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T20:12:58] INFO [django.utils.autoreload.trigger_reload:266] /home/yaswanth/projects/billsnapdec/accounts/views.py changed, reloading.
[2022-12-29T20:12:59] ERROR [django.request.log_response:241] Internal Server Error: /account/just/js/create.js
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yaswanth/projects/billsnapdec/accounts/views.py", line 375, in update_plan
    profile = Profile.objects.get(slug__iexact=userslug)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
accounts.models.Profile.DoesNotExist: Profile matching query does not exist.
[2022-12-29T20:13:05] INFO [root.update_profile:325] yaswanth_ updated profile
[2022-12-29T20:13:05] ERROR [django.request.log_response:241] Internal Server Error: /account/just/js/create.js
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yaswanth/projects/billsnapdec/accounts/views.py", line 375, in update_plan
    profile = Profile.objects.get(slug__iexact=userslug)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
accounts.models.Profile.DoesNotExist: Profile matching query does not exist.
[2022-12-29T20:16:08] ERROR [django.request.log_response:241] Internal Server Error: /account/just/js/create.js
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yaswanth/projects/billsnapdec/accounts/views.py", line 375, in update_plan
    profile = Profile.objects.get(slug__iexact=userslug)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
accounts.models.Profile.DoesNotExist: Profile matching query does not exist.
[2022-12-29T20:20:41] WARNING [django.request.log_response:241] Not Found: /css/searchicon.png
[2022-12-29T20:21:14] INFO [root.deleteapp:74] yaswanth_deleted an app
[2022-12-29T20:21:14] INFO [root.showapps:67] yaswanth_seen the whole applist
[2022-12-29T20:21:16] WARNING [django.request.log_response:241] Not Found: /apps/jin/dashboard/assets/img/ivancik.jpg
[2022-12-29T20:21:21] INFO [root.deleteapp:74] yaswanth_deleted an app
[2022-12-29T20:21:21] INFO [root.showapps:67] yaswanth_seen the whole applist
[2022-12-29T20:21:24] WARNING [django.request.log_response:241] Not Found: /apps/darling/dashboard/assets/img/ivancik.jpg
[2022-12-29T20:21:27] INFO [root.deleteapp:74] yaswanth_deleted an app
[2022-12-29T20:21:27] INFO [root.showapps:67] yaswanth_seen the whole applist
[2022-12-29T20:21:31] WARNING [django.request.log_response:241] Not Found: /apps/yash/dashboard/assets/img/ivancik.jpg
[2022-12-29T20:21:35] INFO [root.deleteapp:74] yaswanth_deleted an app
[2022-12-29T20:21:35] INFO [root.showapps:67] yaswanth_seen the whole applist
[2022-12-29T20:21:38] WARNING [django.request.log_response:241] Not Found: /apps/eee/dashboard/assets/img/ivancik.jpg
[2022-12-29T20:21:42] INFO [root.deleteapp:74] yaswanth_deleted an app
[2022-12-29T20:21:42] INFO [root.showapps:67] yaswanth_seen the whole applist
[2022-12-29T20:21:44] WARNING [django.request.log_response:241] Not Found: /apps/ehe/dashboard/assets/img/ivancik.jpg
[2022-12-29T20:21:46] ERROR [django.request.log_response:241] Internal Server Error: /apps/ehe/appinfo/
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/dashboard/views.py", line 219, in appinfo
    plan = app.plan_set.all().filter(default_for_customer=True)[0]
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/query.py", line 446, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
[2022-12-29T20:22:13] INFO [root.showapps:67] yaswanth_seen the whole applist
[2022-12-29T20:23:08] INFO [root.addapp:56] yaswanth_added an app
[2022-12-29T20:23:08] INFO [root.showapps:67] yaswanth_seen the whole applist
[2022-12-29T20:23:11] WARNING [django.request.log_response:241] Not Found: /apps/app-one/dashboard/assets/img/ivancik.jpg
[2022-12-29T20:23:24] WARNING [django.request.log_response:241] Not Found: /css/searchicon.png
[2022-12-29T20:25:03] WARNING [django.request.log_response:241] Not Found: /css/searchicon.png
[2022-12-29T20:25:09] WARNING [django.request.log_response:241] Not Found: /css/searchicon.png
[2022-12-29T20:25:11] WARNING [django.request.log_response:241] Not Found: /css/searchicon.png
[2022-12-29T20:25:13] WARNING [django.request.log_response:241] Not Found: /css/searchicon.png
[2022-12-29T20:25:15] WARNING [django.request.log_response:241] Not Found: /css/searchicon.png
[2022-12-29T20:25:19] ERROR [django.request.log_response:241] Internal Server Error: /account/app-one/js/create.js
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yaswanth/projects/billsnapdec/accounts/views.py", line 375, in update_plan
    profile = Profile.objects.get(slug__iexact=userslug)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
accounts.models.Profile.DoesNotExist: Profile matching query does not exist.
[2022-12-29T20:26:04] INFO [root.update_profile:325] yaswanth_ updated profile
[2022-12-29T20:26:05] ERROR [django.request.log_response:241] Internal Server Error: /account/app-one/js/create.js
Traceback (most recent call last):
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yaswanth/projects/billsnapdec/accounts/views.py", line 375, in update_plan
    profile = Profile.objects.get(slug__iexact=userslug)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/yaswanth/projects/billsnapdec/env/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
accounts.models.Profile.DoesNotExist: Profile matching query does not exist.
[2023-01-17T19:49:07] WARNING [django.request.log_response:241] Not Found: /favicon.ico/
[2023-01-17T19:49:07] WARNING [django.request.log_response:241] Not Found: /favicon.ico/
[2023-01-17T19:54:57] INFO [root.showapps:67] sony_seen the whole applist
[2023-01-17T19:55:02] WARNING [django.request.log_response:241] Not Found: /apps/app-one/dashboard/assets/img/ivancik.jpg
[2023-01-17T20:07:37] ERROR [django.request.log_response:241] Internal Server Error: /plans/plan/app-one/jZyEQkhlOZ
Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\yash\billsnap\billsnapdec\plans\views.py", line 81, in show_plan
    return render(request, 'plans-panel/plan.html', payload)
  File "D:\yash\billsnap\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'group' with keyword arguments '{'slug': 'app-one', 'groupslug': ''}' not found. 1 pattern(s) tried: ['groups/group/(?P<slug>[^/]+)/(?P<groupslug>[^/]+)\\Z']
[2023-01-17T20:09:48] ERROR [django.request.log_response:241] Internal Server Error: /plans/plan/app-one/jZyEQkhlOZ
Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\yash\billsnap\billsnapdec\plans\views.py", line 81, in show_plan
    return render(request, 'plans-panel/plan.html', payload)
  File "D:\yash\billsnap\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'group' with keyword arguments '{'slug': 'app-one', 'groupslug': ''}' not found. 1 pattern(s) tried: ['groups/group/(?P<slug>[^/]+)/(?P<groupslug>[^/]+)\\Z']
[2023-01-17T20:10:34] ERROR [django.request.log_response:241] Internal Server Error: /plans/plan/app-one/jZyEQkhlOZ
Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'plans'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\yash\billsnap\billsnapdec\plans\views.py", line 81, in show_plan
    return render(request, 'plans-panel/plan.html', payload)
  File "D:\yash\billsnap\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'plans' is not a registered namespace
[2023-01-17T20:14:00] ERROR [django.request.log_response:241] Internal Server Error: /plans/plan/app-one/jZyEQkhlOZ
Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'plans'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\yash\billsnap\billsnapdec\plans\views.py", line 81, in show_plan
    return render(request, 'plans-panel/plan.html', payload)
  File "D:\yash\billsnap\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'plans' is not a registered namespace
[2023-01-17T20:14:01] ERROR [django.request.log_response:241] Internal Server Error: /plans/plan/app-one/jZyEQkhlOZ
Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'plans'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\yash\billsnap\billsnapdec\plans\views.py", line 81, in show_plan
    return render(request, 'plans-panel/plan.html', payload)
  File "D:\yash\billsnap\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'plans' is not a registered namespace
[2023-01-17T20:14:02] ERROR [django.request.log_response:241] Internal Server Error: /plans/plan/app-one/jZyEQkhlOZ
Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'plans'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\yash\billsnap\billsnapdec\plans\views.py", line 81, in show_plan
    return render(request, 'plans-panel/plan.html', payload)
  File "D:\yash\billsnap\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'plans' is not a registered namespace
[2023-01-17T20:14:02] ERROR [django.request.log_response:241] Internal Server Error: /plans/plan/app-one/jZyEQkhlOZ
Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'plans'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\yash\billsnap\billsnapdec\plans\views.py", line 81, in show_plan
    return render(request, 'plans-panel/plan.html', payload)
  File "D:\yash\billsnap\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'plans' is not a registered namespace
[2023-01-17T20:14:02] ERROR [django.request.log_response:241] Internal Server Error: /plans/plan/app-one/jZyEQkhlOZ
Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'plans'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\yash\billsnap\billsnapdec\plans\views.py", line 81, in show_plan
    return render(request, 'plans-panel/plan.html', payload)
  File "D:\yash\billsnap\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'plans' is not a registered namespace
[2023-01-17T20:14:02] ERROR [django.request.log_response:241] Internal Server Error: /plans/plan/app-one/jZyEQkhlOZ
Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'plans'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\yash\billsnap\billsnapdec\plans\views.py", line 81, in show_plan
    return render(request, 'plans-panel/plan.html', payload)
  File "D:\yash\billsnap\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'plans' is not a registered namespace
[2023-01-17T20:17:20] ERROR [django.request.log_response:241] Internal Server Error: /groups/group/app-one/iqdZAk60U3
Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\yash\billsnap\billsnapdec\groups\views.py", line 70, in show_group
    return redirect('groups:group', slug)
  File "D:\yash\billsnap\env\lib\site-packages\django\shortcuts.py", line 48, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "D:\yash\billsnap\env\lib\site-packages\django\shortcuts.py", line 145, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'group' with arguments '('app-one',)' not found. 1 pattern(s) tried: ['groups/group/(?P<slug>[^/]+)/(?P<groupslug>[^/]+)\\Z']
[2023-01-17T20:17:40] WARNING [django.request.log_response:241] Not Found: /css/searchicon.png
[2023-01-17T20:29:50] WARNING [django.request.log_response:241] Not Found: /css/searchicon.png
[2023-01-17T20:32:17] ERROR [django.request.log_response:241] Internal Server Error: /plans/plan/app-one/ggfKqwCODY
Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\yash\billsnap\billsnapdec\plans\views.py", line 81, in show_plan
    return render(request, 'plans-panel/plan.html', payload)
  File "D:\yash\billsnap\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'group' with keyword arguments '{'slug': 'app-one', 'groupslug': ''}' not found. 1 pattern(s) tried: ['groups/group/(?P<slug>[^/]+)/(?P<groupslug>[^/]+)\\Z']
[2023-01-17T20:37:15] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\plans\views.py changed, reloading.
[2023-01-17T20:37:27] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\plans\views.py changed, reloading.
[2023-01-17T20:37:31] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\plans\views.py changed, reloading.
[2023-01-17T20:37:38] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\plans\views.py changed, reloading.
[2023-01-17T20:37:42] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\plans\views.py changed, reloading.
[2023-01-17T20:37:56] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\plans\views.py changed, reloading.
[2023-01-17T20:38:07] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\plans\views.py changed, reloading.
[2023-01-17T20:38:15] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\plans\views.py changed, reloading.
[2023-01-17T20:38:23] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\plans\views.py changed, reloading.
[2023-01-17T20:38:27] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\plans\views.py changed, reloading.
[2023-01-17T20:38:30] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\plans\views.py changed, reloading.
[2023-01-17T20:38:39] ERROR [django.request.log_response:241] Internal Server Error: /plans/plan/app-one/ggfKqwCODY
Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\yash\billsnap\billsnapdec\plans\views.py", line 74, in show_plan
    existing_users = Profile.objects.filter(apps=plan.app).exclude(plan=plan)
  File "D:\yash\billsnap\env\lib\site-packages\django\db\models\query.py", line 1428, in exclude
    return self._filter_or_exclude(True, args, kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\db\models\query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\db\models\query.py", line 1443, in _filter_or_exclude_inplace
    self._query.add_q(~Q(*args, **kwargs))
  File "D:\yash\billsnap\env\lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\yash\billsnap\env\lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "D:\yash\billsnap\env\lib\site-packages\django\db\models\sql\query.py", line 1407, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "D:\yash\billsnap\env\lib\site-packages\django\db\models\sql\query.py", line 1217, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "D:\yash\billsnap\env\lib\site-packages\django\db\models\sql\query.py", line 1709, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'plan' into field. Choices are: admin, apps, contact_designation, contact_email, contact_landline, contact_mobile, contact_person, contact_phnum, emergency_altmobile, emergency_altofficeaddress, emergency_altperson, emergency_mobile, emergency_officeaddress, emergency_person, full_name, group, id, info_created_at, info_updated_at, paid, plan_active, plans, se_coins, slug, status, user, user_id, user_notifications, utility_address, utility_country, utility_district, utility_name, utility_postalcode, utility_short_name, utility_state
[2023-01-17T20:39:25] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\plans\views.py changed, reloading.
[2023-01-17T20:39:31] ERROR [django.request.log_response:241] Internal Server Error: /plans/plan/app-one/ggfKqwCODY
Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'plans'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\yash\billsnap\billsnapdec\plans\views.py", line 83, in show_plan
    return render(request, 'plans-panel/plan.html', payload)
  File "D:\yash\billsnap\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'plans' is not a registered namespace
[2023-01-17T20:49:32] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\plans\views.py changed, reloading.
[2023-01-17T20:49:36] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\plans\views.py changed, reloading.
[2023-01-17T20:49:52] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\plans\views.py changed, reloading.
[2023-01-17T20:49:55] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\plans\views.py changed, reloading.
[2023-01-17T20:52:23] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\plans\views.py changed, reloading.
[2023-01-17T20:52:39] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\plans\views.py changed, reloading.
[2023-01-17T20:52:46] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\plans\views.py changed, reloading.
[2023-01-17T20:52:49] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\plans\views.py changed, reloading.
[2023-01-17T20:53:04] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\plans\views.py changed, reloading.
[2023-01-17T20:53:13] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\plans\views.py changed, reloading.
[2023-01-17T20:53:18] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\plans\views.py changed, reloading.
[2023-01-17T20:53:22] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\plans\views.py changed, reloading.
[2023-01-17T20:53:44] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\plans\views.py changed, reloading.
[2023-01-17T20:53:47] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\plans\views.py changed, reloading.
[2023-01-17T20:57:20] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\plans\views.py changed, reloading.
[2023-01-17T20:57:26] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\plans\views.py changed, reloading.
[2023-01-17T20:57:30] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\plans\views.py changed, reloading.
