[2022-12-05T00:23:15] ERROR [django.request.log_response:241] Internal Server Error: /apps/editapp/instagram
Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\yash\billsnap\env\lib\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: apps_applists.slug

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\yash\billsnap\billsnapdec\apps\views.py", line 95, in editapp
    app.save()
  File "D:\yash\billsnap\billsnapdec\apps\models.py", line 33, in save
    super(applists, self).save()
  File "D:\yash\billsnap\env\lib\site-packages\django\db\models\base.py", line 812, in save
    self.save_base(
  File "D:\yash\billsnap\env\lib\site-packages\django\db\models\base.py", line 863, in save_base
    updated = self._save_table(
  File "D:\yash\billsnap\env\lib\site-packages\django\db\models\base.py", line 1006, in _save_table
    results = self._do_insert(
  File "D:\yash\billsnap\env\lib\site-packages\django\db\models\base.py", line 1047, in _do_insert
    return manager._insert(
  File "D:\yash\billsnap\env\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\db\models\query.py", line 1790, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\yash\billsnap\env\lib\site-packages\django\db\models\sql\compiler.py", line 1660, in execute_sql
    cursor.execute(sql, params)
  File "D:\yash\billsnap\env\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "D:\yash\billsnap\env\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\yash\billsnap\env\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\yash\billsnap\env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "D:\yash\billsnap\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\yash\billsnap\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\yash\billsnap\env\lib\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: apps_applists.slug
[2022-12-05T00:23:39] ERROR [django.request.log_response:241] Internal Server Error: /apps/editapp/instagram
Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\yash\billsnap\env\lib\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: apps_applists.slug

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\yash\billsnap\billsnapdec\apps\views.py", line 95, in editapp
    app.save()
  File "D:\yash\billsnap\billsnapdec\apps\models.py", line 33, in save
    super(applists, self).save()
  File "D:\yash\billsnap\env\lib\site-packages\django\db\models\base.py", line 812, in save
    self.save_base(
  File "D:\yash\billsnap\env\lib\site-packages\django\db\models\base.py", line 863, in save_base
    updated = self._save_table(
  File "D:\yash\billsnap\env\lib\site-packages\django\db\models\base.py", line 1006, in _save_table
    results = self._do_insert(
  File "D:\yash\billsnap\env\lib\site-packages\django\db\models\base.py", line 1047, in _do_insert
    return manager._insert(
  File "D:\yash\billsnap\env\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\db\models\query.py", line 1790, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\yash\billsnap\env\lib\site-packages\django\db\models\sql\compiler.py", line 1660, in execute_sql
    cursor.execute(sql, params)
  File "D:\yash\billsnap\env\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "D:\yash\billsnap\env\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\yash\billsnap\env\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\yash\billsnap\env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "D:\yash\billsnap\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\yash\billsnap\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\yash\billsnap\env\lib\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: apps_applists.slug
[2022-12-05T00:24:04] INFO [root.deleteapp:77] neha_deleted an app
[2022-12-05T00:24:04] INFO [root.showapps:70] neha_seen the whole applist
[2022-12-05T00:24:18] WARNING [django.request.log_response:241] Not Found: /apps/instagram/dashboard/assets/img/ivancik.jpg
[2022-12-05T00:24:32] ERROR [django.request.log_response:241] Internal Server Error: /apps/editapp/instagram
Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\yash\billsnap\env\lib\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: apps_applists.slug

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\yash\billsnap\billsnapdec\apps\views.py", line 95, in editapp
    app.save()
  File "D:\yash\billsnap\billsnapdec\apps\models.py", line 33, in save
    super(applists, self).save()
  File "D:\yash\billsnap\env\lib\site-packages\django\db\models\base.py", line 812, in save
    self.save_base(
  File "D:\yash\billsnap\env\lib\site-packages\django\db\models\base.py", line 863, in save_base
    updated = self._save_table(
  File "D:\yash\billsnap\env\lib\site-packages\django\db\models\base.py", line 1006, in _save_table
    results = self._do_insert(
  File "D:\yash\billsnap\env\lib\site-packages\django\db\models\base.py", line 1047, in _do_insert
    return manager._insert(
  File "D:\yash\billsnap\env\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\db\models\query.py", line 1790, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\yash\billsnap\env\lib\site-packages\django\db\models\sql\compiler.py", line 1660, in execute_sql
    cursor.execute(sql, params)
  File "D:\yash\billsnap\env\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "D:\yash\billsnap\env\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\yash\billsnap\env\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\yash\billsnap\env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "D:\yash\billsnap\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\yash\billsnap\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\yash\billsnap\env\lib\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: apps_applists.slug
[2022-12-05T00:25:38] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\apps\views.py changed, reloading.
[2022-12-05T00:25:47] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\apps\views.py changed, reloading.
[2022-12-05T00:25:55] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\apps\views.py changed, reloading.
[2022-12-05T00:26:01] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\apps\views.py changed, reloading.
[2022-12-05T00:26:06] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\apps\views.py changed, reloading.
[2022-12-05T00:26:10] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\apps\views.py changed, reloading.
[2022-12-05T00:26:25] INFO [root.editapp:95] neha_edited an app
[2022-12-05T00:32:12] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\dashboard\views.py changed, reloading.
[2022-12-05T00:32:24] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\dashboard\views.py changed, reloading.
[2022-12-05T00:33:52] ERROR [django.request.log_response:241] Internal Server Error: /apps/instagram/appinfo/
Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\yash\billsnap\billsnapdec\dashboard\views.py", line 209, in appinfo
    plan = app.plan_set.all().filter(default_for_customer=True)[0]
  File "D:\yash\billsnap\env\lib\site-packages\django\db\models\query.py", line 446, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
[2022-12-05T00:34:16] ERROR [django.request.log_response:241] Internal Server Error: /apps/ehee/appinfo/
Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\yash\billsnap\billsnapdec\dashboard\views.py", line 208, in appinfo
    app = applists.objects.get(slug=slug)
  File "D:\yash\billsnap\env\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
apps.models.applists.DoesNotExist: applists matching query does not exist.
[2022-12-05T00:34:20] ERROR [django.request.log_response:241] Internal Server Error: /apps/eheee/appinfo/
Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\yash\billsnap\billsnapdec\dashboard\views.py", line 208, in appinfo
    app = applists.objects.get(slug=slug)
  File "D:\yash\billsnap\env\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
apps.models.applists.DoesNotExist: applists matching query does not exist.
[2022-12-05T00:34:25] INFO [root.showapps:70] neha_seen the whole applist
[2022-12-05T00:34:32] WARNING [django.request.log_response:241] Not Found: /apps/darling/dashboard/assets/img/ivancik.jpg
[2022-12-05T00:39:44] INFO [root.showapps:70] neha_seen the whole applist
[2022-12-05T00:42:09] INFO [root.showapps:70] neha_seen the whole applist
[2022-12-05T00:42:27] WARNING [django.request.log_response:241] Not Found: /apps/darling/dashboard/assets/img/ivancik.jpg
[2022-12-05T00:43:05] WARNING [django.request.log_response:241] Not Found: /apps/darling/dashboard/assets/img/ivancik.jpg
[2022-12-05T00:47:20] WARNING [django.request.log_response:241] Not Found: /favicon.ico
[2022-12-05T00:50:30] WARNING [django.request.log_response:241] Not Found: /favicon.ico
[2022-12-05T00:52:49] WARNING [django.request.log_response:241] Not Found: /apps/darling/dashboard/assets/img/ivancik.jpg
[2022-12-05T01:00:22] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\groups\views.py changed, reloading.
[2022-12-05T01:07:01] WARNING [django.request.log_response:241] Not Found: /css/searchicon.png
[2022-12-05T01:07:21] DEBUG [PIL.PngImagePlugin.call:201] STREAM b'IHDR' 16 13
[2022-12-05T01:07:21] DEBUG [PIL.PngImagePlugin.call:201] STREAM b'sRGB' 41 1
[2022-12-05T01:07:21] DEBUG [PIL.PngImagePlugin.call:201] STREAM b'gAMA' 54 4
[2022-12-05T01:07:21] DEBUG [PIL.PngImagePlugin.call:201] STREAM b'IDAT' 70 65466
[2022-12-05T01:07:21] DEBUG [PIL.Image.init:369] Importing BlpImagePlugin
[2022-12-05T01:07:21] DEBUG [PIL.Image.init:369] Importing BmpImagePlugin
[2022-12-05T01:07:21] DEBUG [PIL.Image.init:369] Importing BufrStubImagePlugin
[2022-12-05T01:07:21] DEBUG [PIL.Image.init:369] Importing CurImagePlugin
[2022-12-05T01:07:21] DEBUG [PIL.Image.init:369] Importing DcxImagePlugin
[2022-12-05T01:07:21] DEBUG [PIL.Image.init:369] Importing DdsImagePlugin
[2022-12-05T01:07:21] DEBUG [PIL.Image.init:369] Importing EpsImagePlugin
[2022-12-05T01:07:21] DEBUG [PIL.Image.init:369] Importing FitsImagePlugin
[2022-12-05T01:07:21] DEBUG [PIL.Image.init:369] Importing FitsStubImagePlugin
[2022-12-05T01:07:21] DEBUG [PIL.Image.init:369] Importing FliImagePlugin
[2022-12-05T01:07:21] DEBUG [PIL.Image.init:369] Importing FpxImagePlugin
[2022-12-05T01:07:21] DEBUG [PIL.Image.init:372] Image: failed to import FpxImagePlugin: No module named 'olefile'
[2022-12-05T01:07:21] DEBUG [PIL.Image.init:369] Importing FtexImagePlugin
[2022-12-05T01:07:21] DEBUG [PIL.Image.init:369] Importing GbrImagePlugin
[2022-12-05T01:07:21] DEBUG [PIL.Image.init:369] Importing GifImagePlugin
[2022-12-05T01:07:21] DEBUG [PIL.Image.init:369] Importing GribStubImagePlugin
[2022-12-05T01:07:21] DEBUG [PIL.Image.init:369] Importing Hdf5StubImagePlugin
[2022-12-05T01:07:21] DEBUG [PIL.Image.init:369] Importing IcnsImagePlugin
[2022-12-05T01:07:21] DEBUG [PIL.Image.init:369] Importing IcoImagePlugin
[2022-12-05T01:07:21] DEBUG [PIL.Image.init:369] Importing ImImagePlugin
[2022-12-05T01:07:21] DEBUG [PIL.Image.init:369] Importing ImtImagePlugin
[2022-12-05T01:07:21] DEBUG [PIL.Image.init:369] Importing IptcImagePlugin
[2022-12-05T01:07:21] DEBUG [PIL.Image.init:369] Importing JpegImagePlugin
[2022-12-05T01:07:21] DEBUG [PIL.Image.init:369] Importing Jpeg2KImagePlugin
[2022-12-05T01:07:21] DEBUG [PIL.Image.init:369] Importing McIdasImagePlugin
[2022-12-05T01:07:21] DEBUG [PIL.Image.init:369] Importing MicImagePlugin
[2022-12-05T01:07:21] DEBUG [PIL.Image.init:372] Image: failed to import MicImagePlugin: No module named 'olefile'
[2022-12-05T01:07:21] DEBUG [PIL.Image.init:369] Importing MpegImagePlugin
[2022-12-05T01:07:21] DEBUG [PIL.Image.init:369] Importing MpoImagePlugin
[2022-12-05T01:07:21] DEBUG [PIL.Image.init:369] Importing MspImagePlugin
[2022-12-05T01:07:21] DEBUG [PIL.Image.init:369] Importing PalmImagePlugin
[2022-12-05T01:07:21] DEBUG [PIL.Image.init:369] Importing PcdImagePlugin
[2022-12-05T01:07:21] DEBUG [PIL.Image.init:369] Importing PcxImagePlugin
[2022-12-05T01:07:21] DEBUG [PIL.Image.init:369] Importing PdfImagePlugin
[2022-12-05T01:07:21] DEBUG [PIL.Image.init:369] Importing PixarImagePlugin
[2022-12-05T01:07:21] DEBUG [PIL.Image.init:369] Importing PngImagePlugin
[2022-12-05T01:07:21] DEBUG [PIL.Image.init:369] Importing PpmImagePlugin
[2022-12-05T01:07:21] DEBUG [PIL.Image.init:369] Importing PsdImagePlugin
[2022-12-05T01:07:21] DEBUG [PIL.Image.init:369] Importing SgiImagePlugin
[2022-12-05T01:07:21] DEBUG [PIL.Image.init:369] Importing SpiderImagePlugin
[2022-12-05T01:07:21] DEBUG [PIL.Image.init:369] Importing SunImagePlugin
[2022-12-05T01:07:21] DEBUG [PIL.Image.init:369] Importing TgaImagePlugin
[2022-12-05T01:07:21] DEBUG [PIL.Image.init:369] Importing TiffImagePlugin
[2022-12-05T01:07:21] DEBUG [PIL.Image.init:369] Importing WebPImagePlugin
[2022-12-05T01:07:22] DEBUG [PIL.Image.init:369] Importing WmfImagePlugin
[2022-12-05T01:07:22] DEBUG [PIL.Image.init:369] Importing XbmImagePlugin
[2022-12-05T01:07:22] DEBUG [PIL.Image.init:369] Importing XpmImagePlugin
[2022-12-05T01:07:22] DEBUG [PIL.Image.init:369] Importing XVThumbImagePlugin
[2022-12-05T01:07:22] ERROR [django.request.log_response:241] Internal Server Error: /account/create-notification/darling/
Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\yash\billsnap\billsnapdec\accounts\views.py", line 325, in create_notification
    return redirect('show_profile', slug=profile.slug, appslug=slug)
  File "D:\yash\billsnap\env\lib\site-packages\django\shortcuts.py", line 48, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "D:\yash\billsnap\env\lib\site-packages\django\shortcuts.py", line 145, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'show_profile' not found. 'show_profile' is not a valid view function or pattern name.
[2022-12-05T01:08:38] INFO [root.update_profile:284] neha_ updated profile
[2022-12-05T01:08:38] ERROR [django.request.log_response:241] Internal Server Error: /account/yaswanth/edit/
Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\yash\billsnap\billsnapdec\accounts\views.py", line 285, in update_profile
    return HttpResponseRedirect(reverse('accounts:show-profile', kwargs={'slug':slug}))
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'show-profile' with keyword arguments '{'slug': 'yaswanth'}' not found. 1 pattern(s) tried: ['account/(?P<slug>[^/]+)/(?P<appslug>[^/]+)\\Z']
[2022-12-05T01:09:58] WARNING [django.request.log_response:241] Not Found: /css/searchicon.png
[2022-12-05T01:10:11] INFO [root.logout:189] neha_ logged out
[2022-12-05T01:10:32] INFO [root.showapps:70] yaswanth_seen the whole applist
[2022-12-05T01:10:35] WARNING [django.request.log_response:241] Not Found: /apps/darling/dashboard/assets/img/ivancik.jpg
[2022-12-05T01:11:41] ERROR [django.request.log_response:241] Internal Server Error: /plans/update-plan/neha
Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\yash\billsnap\billsnapdec\plans\views.py", line 110, in update_user_plan
    current_plan = profile.plan
AttributeError: 'Profile' object has no attribute 'plan'
[2022-12-05T01:18:24] WARNING [django.request.log_response:241] Not Found: /css/searchicon.png
[2022-12-05T01:20:50] ERROR [django.request.log_response:241] Internal Server Error: /account/yaswanth/darling
Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\yash\billsnap\env\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\yash\billsnap\env\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\loader_tags.py", line 208, in render
    return template.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 177, in render
    return self._render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'dashboard' with arguments '('',)' not found. 1 pattern(s) tried: ['apps/(?P<slug>[^/]+)/dashboard/\\Z']
[2022-12-05T01:20:53] ERROR [django.request.log_response:241] Internal Server Error: /account/yaswanth/darling
Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\yash\billsnap\env\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\yash\billsnap\env\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\loader_tags.py", line 208, in render
    return template.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 177, in render
    return self._render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'dashboard' with arguments '('',)' not found. 1 pattern(s) tried: ['apps/(?P<slug>[^/]+)/dashboard/\\Z']
[2022-12-05T01:21:37] ERROR [django.request.log_response:241] Internal Server Error: /account/yaswanth/darling
Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\yash\billsnap\env\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\yash\billsnap\env\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\loader_tags.py", line 208, in render
    return template.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 177, in render
    return self._render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'dashboard' with arguments '('',)' not found. 1 pattern(s) tried: ['apps/(?P<slug>[^/]+)/dashboard/\\Z']
[2022-12-05T01:23:20] WARNING [django.request.log_response:241] Not Found: /css/searchicon.png
[2022-12-05T01:24:30] WARNING [django.request.log_response:241] Not Found: /css/searchicon.png
[2022-12-05T01:25:43] WARNING [django.request.log_response:241] Not Found: /css/searchicon.png
[2022-12-05T01:27:00] WARNING [django.request.log_response:241] Not Found: /css/searchicon.png
[2022-12-05T01:35:17] WARNING [django.request.log_response:241] Not Found: /css/searchicon.png
[2022-12-05T01:35:19] WARNING [django.request.log_response:241] Not Found: /css/searchicon.png
[2022-12-05T01:35:53] WARNING [django.request.log_response:241] Not Found: /css/searchicon.png
[2022-12-05T01:36:08] WARNING [django.request.log_response:241] Not Found: /css/searchicon.png
[2022-12-05T01:37:13] WARNING [django.request.log_response:241] Not Found: /css/searchicon.png
[2022-12-05T01:37:14] WARNING [django.request.log_response:241] Not Found: /favicon.ico
[2022-12-05T01:37:43] WARNING [django.request.log_response:241] Not Found: /css/searchicon.png
[2022-12-05T01:37:44] WARNING [django.request.log_response:241] Not Found: /favicon.ico
[2022-12-05T01:38:10] WARNING [django.request.log_response:241] Not Found: /css/searchicon.png
[2022-12-05T01:47:21] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\plans\urls.py changed, reloading.
[2022-12-05T01:47:39] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\plans\urls.py changed, reloading.
[2022-12-05T01:48:17] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\plans\views.py changed, reloading.
[2022-12-05T01:48:27] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\plans\views.py changed, reloading.
[2022-12-05T01:48:40] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\plans\views.py changed, reloading.
[2022-12-05T01:48:50] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\plans\views.py changed, reloading.
[2022-12-05T01:48:56] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\plans\views.py changed, reloading.
[2022-12-05T01:49:01] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\plans\views.py changed, reloading.
[2022-12-05T01:56:45] WARNING [django.request.log_response:241] Not Found: /css/searchicon.png
[2022-12-05T02:01:45] INFO [root.logout:189] yaswanth_ logged out
[2022-12-05T02:14:07] WARNING [django.request.log_response:241] Not Found: /favicon.ico
[2022-12-05T02:15:47] INFO [root.showapps:70] yaswanth_seen the whole applist
[2022-12-05T02:15:53] WARNING [django.request.log_response:241] Not Found: /apps/darling/dashboard/assets/img/ivancik.jpg
[2022-12-05T02:17:27] WARNING [django.request.log_response:241] Not Found: /css/searchicon.png
[2022-12-05T02:19:05] WARNING [django.request.log_response:241] Not Found: /css/searchicon.png
[2022-12-05T02:21:29] ERROR [django.request.log_response:241] Internal Server Error: /account/yaswanth/edit/
Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\yash\billsnap\billsnapdec\accounts\views.py", line 288, in update_profile
    return render(request, 'editprofile.html', {'profile': profile})
  File "D:\yash\billsnap\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'update' not found. 'update' is not a valid view function or pattern name.
[2022-12-05T02:23:59] ERROR [django.request.log_response:241] Internal Server Error: /account/yaswanth/edit/
Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\yash\billsnap\billsnapdec\accounts\views.py", line 288, in update_profile
    return render(request, 'editprofile.html', {'profile': profile})
  File "D:\yash\billsnap\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'update-profile' not found. 'update-profile' is not a valid view function or pattern name.
[2022-12-05T02:24:40] INFO [root.update_profile:284] yaswanth_ updated profile
[2022-12-05T02:24:40] ERROR [django.request.log_response:241] Internal Server Error: /account/yaswanth/edit/
Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\yash\billsnap\billsnapdec\accounts\views.py", line 285, in update_profile
    return HttpResponseRedirect(reverse('accounts:show-profile', kwargs={'slug':slug}))
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'show-profile' with keyword arguments '{'slug': 'yaswanth'}' not found. 1 pattern(s) tried: ['account/(?P<slug>[^/]+)/(?P<appslug>[^/]+)\\Z']
[2022-12-05T02:26:02] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\accounts\views.py changed, reloading.
[2022-12-05T02:26:09] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\accounts\views.py changed, reloading.
[2022-12-05T02:28:51] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\accounts\urls.py changed, reloading.
[2022-12-05T02:29:08] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\accounts\views.py changed, reloading.
[2022-12-05T02:29:18] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\accounts\views.py changed, reloading.
[2022-12-05T02:29:29] ERROR [django.request.log_response:241] Internal Server Error: /account/yaswanth/darling
Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\yash\billsnap\env\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\yash\billsnap\env\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'update-profile' with arguments '('yaswanth',)' not found. 1 pattern(s) tried: ['account/(?P<slug>[^/]+)/edit/(?P<appslug>[^/]+)\\Z']
[2022-12-05T02:30:01] ERROR [django.request.log_response:241] Internal Server Error: /account/yaswanth/edit/darling
Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\yash\billsnap\billsnapdec\accounts\views.py", line 288, in update_profile
    return render(request, 'editprofile.html', {'profile': profile})
  File "D:\yash\billsnap\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'update-profile' with arguments '('yaswanth',)' not found. 1 pattern(s) tried: ['account/(?P<slug>[^/]+)/edit/(?P<appslug>[^/]+)\\Z']
[2022-12-05T02:31:27] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\accounts\views.py changed, reloading.
[2022-12-05T02:31:50] INFO [root.update_profile:284] yaswanth_ updated profile
[2022-12-05T02:35:47] INFO [root.update_profile:284] yaswanth_ updated profile
[2022-12-05T02:35:59] INFO [root.update_profile:284] yaswanth_ updated profile
[2022-12-05T02:38:59] DEBUG [PIL.PngImagePlugin.call:201] STREAM b'IHDR' 16 13
[2022-12-05T02:38:59] DEBUG [PIL.PngImagePlugin.call:201] STREAM b'sRGB' 41 1
[2022-12-05T02:38:59] DEBUG [PIL.PngImagePlugin.call:201] STREAM b'gAMA' 54 4
[2022-12-05T02:38:59] DEBUG [PIL.PngImagePlugin.call:201] STREAM b'IDAT' 70 65466
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:369] Importing BlpImagePlugin
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:369] Importing BmpImagePlugin
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:369] Importing BufrStubImagePlugin
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:369] Importing CurImagePlugin
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:369] Importing DcxImagePlugin
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:369] Importing DdsImagePlugin
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:369] Importing EpsImagePlugin
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:369] Importing FitsImagePlugin
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:369] Importing FitsStubImagePlugin
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:369] Importing FliImagePlugin
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:369] Importing FpxImagePlugin
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:372] Image: failed to import FpxImagePlugin: No module named 'olefile'
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:369] Importing FtexImagePlugin
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:369] Importing GbrImagePlugin
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:369] Importing GifImagePlugin
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:369] Importing GribStubImagePlugin
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:369] Importing Hdf5StubImagePlugin
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:369] Importing IcnsImagePlugin
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:369] Importing IcoImagePlugin
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:369] Importing ImImagePlugin
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:369] Importing ImtImagePlugin
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:369] Importing IptcImagePlugin
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:369] Importing JpegImagePlugin
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:369] Importing Jpeg2KImagePlugin
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:369] Importing McIdasImagePlugin
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:369] Importing MicImagePlugin
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:372] Image: failed to import MicImagePlugin: No module named 'olefile'
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:369] Importing MpegImagePlugin
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:369] Importing MpoImagePlugin
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:369] Importing MspImagePlugin
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:369] Importing PalmImagePlugin
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:369] Importing PcdImagePlugin
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:369] Importing PcxImagePlugin
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:369] Importing PdfImagePlugin
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:369] Importing PixarImagePlugin
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:369] Importing PngImagePlugin
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:369] Importing PpmImagePlugin
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:369] Importing PsdImagePlugin
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:369] Importing SgiImagePlugin
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:369] Importing SpiderImagePlugin
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:369] Importing SunImagePlugin
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:369] Importing TgaImagePlugin
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:369] Importing TiffImagePlugin
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:369] Importing WebPImagePlugin
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:369] Importing WmfImagePlugin
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:369] Importing XbmImagePlugin
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:369] Importing XpmImagePlugin
[2022-12-05T02:38:59] DEBUG [PIL.Image.init:369] Importing XVThumbImagePlugin
[2022-12-05T02:38:59] ERROR [django.request.log_response:241] Internal Server Error: /account/create-notification/darling/
Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\yash\billsnap\billsnapdec\accounts\views.py", line 325, in create_notification
    return redirect('show_profile', slug=profile.slug, appslug=slug)
  File "D:\yash\billsnap\env\lib\site-packages\django\shortcuts.py", line 48, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "D:\yash\billsnap\env\lib\site-packages\django\shortcuts.py", line 145, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'show_profile' not found. 'show_profile' is not a valid view function or pattern name.
[2022-12-05T02:39:35] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\accounts\views.py changed, reloading.
[2022-12-05T02:39:57] DEBUG [PIL.PngImagePlugin.call:201] STREAM b'IHDR' 16 13
[2022-12-05T02:39:57] DEBUG [PIL.PngImagePlugin.call:201] STREAM b'sRGB' 41 1
[2022-12-05T02:39:57] DEBUG [PIL.PngImagePlugin.call:201] STREAM b'gAMA' 54 4
[2022-12-05T02:39:57] DEBUG [PIL.PngImagePlugin.call:201] STREAM b'IDAT' 70 65466
[2022-12-05T02:39:57] DEBUG [PIL.Image.init:369] Importing BlpImagePlugin
[2022-12-05T02:39:57] DEBUG [PIL.Image.init:369] Importing BmpImagePlugin
[2022-12-05T02:39:57] DEBUG [PIL.Image.init:369] Importing BufrStubImagePlugin
[2022-12-05T02:39:57] DEBUG [PIL.Image.init:369] Importing CurImagePlugin
[2022-12-05T02:39:57] DEBUG [PIL.Image.init:369] Importing DcxImagePlugin
[2022-12-05T02:39:57] DEBUG [PIL.Image.init:369] Importing DdsImagePlugin
[2022-12-05T02:39:57] DEBUG [PIL.Image.init:369] Importing EpsImagePlugin
[2022-12-05T02:39:57] DEBUG [PIL.Image.init:369] Importing FitsImagePlugin
[2022-12-05T02:39:57] DEBUG [PIL.Image.init:369] Importing FitsStubImagePlugin
[2022-12-05T02:39:57] DEBUG [PIL.Image.init:369] Importing FliImagePlugin
[2022-12-05T02:39:57] DEBUG [PIL.Image.init:369] Importing FpxImagePlugin
[2022-12-05T02:39:57] DEBUG [PIL.Image.init:372] Image: failed to import FpxImagePlugin: No module named 'olefile'
[2022-12-05T02:39:57] DEBUG [PIL.Image.init:369] Importing FtexImagePlugin
[2022-12-05T02:39:57] DEBUG [PIL.Image.init:369] Importing GbrImagePlugin
[2022-12-05T02:39:57] DEBUG [PIL.Image.init:369] Importing GifImagePlugin
[2022-12-05T02:39:57] DEBUG [PIL.Image.init:369] Importing GribStubImagePlugin
[2022-12-05T02:39:57] DEBUG [PIL.Image.init:369] Importing Hdf5StubImagePlugin
[2022-12-05T02:39:57] DEBUG [PIL.Image.init:369] Importing IcnsImagePlugin
[2022-12-05T02:39:57] DEBUG [PIL.Image.init:369] Importing IcoImagePlugin
[2022-12-05T02:39:57] DEBUG [PIL.Image.init:369] Importing ImImagePlugin
[2022-12-05T02:39:57] DEBUG [PIL.Image.init:369] Importing ImtImagePlugin
[2022-12-05T02:39:57] DEBUG [PIL.Image.init:369] Importing IptcImagePlugin
[2022-12-05T02:39:57] DEBUG [PIL.Image.init:369] Importing JpegImagePlugin
[2022-12-05T02:39:57] DEBUG [PIL.Image.init:369] Importing Jpeg2KImagePlugin
[2022-12-05T02:39:57] DEBUG [PIL.Image.init:369] Importing McIdasImagePlugin
[2022-12-05T02:39:57] DEBUG [PIL.Image.init:369] Importing MicImagePlugin
[2022-12-05T02:39:57] DEBUG [PIL.Image.init:372] Image: failed to import MicImagePlugin: No module named 'olefile'
[2022-12-05T02:39:57] DEBUG [PIL.Image.init:369] Importing MpegImagePlugin
[2022-12-05T02:39:57] DEBUG [PIL.Image.init:369] Importing MpoImagePlugin
[2022-12-05T02:39:57] DEBUG [PIL.Image.init:369] Importing MspImagePlugin
[2022-12-05T02:39:58] DEBUG [PIL.Image.init:369] Importing PalmImagePlugin
[2022-12-05T02:39:58] DEBUG [PIL.Image.init:369] Importing PcdImagePlugin
[2022-12-05T02:39:58] DEBUG [PIL.Image.init:369] Importing PcxImagePlugin
[2022-12-05T02:39:58] DEBUG [PIL.Image.init:369] Importing PdfImagePlugin
[2022-12-05T02:39:58] DEBUG [PIL.Image.init:369] Importing PixarImagePlugin
[2022-12-05T02:39:58] DEBUG [PIL.Image.init:369] Importing PngImagePlugin
[2022-12-05T02:39:58] DEBUG [PIL.Image.init:369] Importing PpmImagePlugin
[2022-12-05T02:39:58] DEBUG [PIL.Image.init:369] Importing PsdImagePlugin
[2022-12-05T02:39:58] DEBUG [PIL.Image.init:369] Importing SgiImagePlugin
[2022-12-05T02:39:58] DEBUG [PIL.Image.init:369] Importing SpiderImagePlugin
[2022-12-05T02:39:58] DEBUG [PIL.Image.init:369] Importing SunImagePlugin
[2022-12-05T02:39:58] DEBUG [PIL.Image.init:369] Importing TgaImagePlugin
[2022-12-05T02:39:58] DEBUG [PIL.Image.init:369] Importing TiffImagePlugin
[2022-12-05T02:39:58] DEBUG [PIL.Image.init:369] Importing WebPImagePlugin
[2022-12-05T02:39:58] DEBUG [PIL.Image.init:369] Importing WmfImagePlugin
[2022-12-05T02:39:58] DEBUG [PIL.Image.init:369] Importing XbmImagePlugin
[2022-12-05T02:39:58] DEBUG [PIL.Image.init:369] Importing XpmImagePlugin
[2022-12-05T02:39:58] DEBUG [PIL.Image.init:369] Importing XVThumbImagePlugin
[2022-12-05T02:39:58] ERROR [django.request.log_response:241] Internal Server Error: /account/create-notification/darling/
Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\yash\billsnap\billsnapdec\accounts\views.py", line 325, in create_notification
    return redirect('accounts:show_profile', slug=profile.slug, appslug=slug)
  File "D:\yash\billsnap\env\lib\site-packages\django\shortcuts.py", line 48, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "D:\yash\billsnap\env\lib\site-packages\django\shortcuts.py", line 145, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'show_profile' not found. 'show_profile' is not a valid view function or pattern name.
[2022-12-05T02:40:29] DEBUG [PIL.PngImagePlugin.call:201] STREAM b'IHDR' 16 13
[2022-12-05T02:40:29] DEBUG [PIL.PngImagePlugin.call:201] STREAM b'sRGB' 41 1
[2022-12-05T02:40:29] DEBUG [PIL.PngImagePlugin.call:201] STREAM b'gAMA' 54 4
[2022-12-05T02:40:29] DEBUG [PIL.PngImagePlugin.call:201] STREAM b'IDAT' 70 65466
[2022-12-05T02:40:29] ERROR [django.request.log_response:241] Internal Server Error: /account/create-notification/darling/
Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\yash\billsnap\billsnapdec\accounts\views.py", line 325, in create_notification
    return redirect('accounts:show_profile', slug=profile.slug, appslug=slug)
  File "D:\yash\billsnap\env\lib\site-packages\django\shortcuts.py", line 48, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "D:\yash\billsnap\env\lib\site-packages\django\shortcuts.py", line 145, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'show_profile' not found. 'show_profile' is not a valid view function or pattern name.
[2022-12-05T02:41:02] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\accounts\views.py changed, reloading.
[2022-12-05T02:41:10] DEBUG [PIL.PngImagePlugin.call:201] STREAM b'IHDR' 16 13
[2022-12-05T02:41:10] DEBUG [PIL.PngImagePlugin.call:201] STREAM b'sRGB' 41 1
[2022-12-05T02:41:10] DEBUG [PIL.PngImagePlugin.call:201] STREAM b'gAMA' 54 4
[2022-12-05T02:41:10] DEBUG [PIL.PngImagePlugin.call:201] STREAM b'IDAT' 70 65466
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:369] Importing BlpImagePlugin
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:369] Importing BmpImagePlugin
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:369] Importing BufrStubImagePlugin
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:369] Importing CurImagePlugin
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:369] Importing DcxImagePlugin
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:369] Importing DdsImagePlugin
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:369] Importing EpsImagePlugin
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:369] Importing FitsImagePlugin
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:369] Importing FitsStubImagePlugin
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:369] Importing FliImagePlugin
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:369] Importing FpxImagePlugin
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:372] Image: failed to import FpxImagePlugin: No module named 'olefile'
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:369] Importing FtexImagePlugin
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:369] Importing GbrImagePlugin
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:369] Importing GifImagePlugin
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:369] Importing GribStubImagePlugin
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:369] Importing Hdf5StubImagePlugin
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:369] Importing IcnsImagePlugin
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:369] Importing IcoImagePlugin
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:369] Importing ImImagePlugin
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:369] Importing ImtImagePlugin
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:369] Importing IptcImagePlugin
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:369] Importing JpegImagePlugin
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:369] Importing Jpeg2KImagePlugin
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:369] Importing McIdasImagePlugin
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:369] Importing MicImagePlugin
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:372] Image: failed to import MicImagePlugin: No module named 'olefile'
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:369] Importing MpegImagePlugin
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:369] Importing MpoImagePlugin
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:369] Importing MspImagePlugin
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:369] Importing PalmImagePlugin
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:369] Importing PcdImagePlugin
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:369] Importing PcxImagePlugin
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:369] Importing PdfImagePlugin
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:369] Importing PixarImagePlugin
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:369] Importing PngImagePlugin
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:369] Importing PpmImagePlugin
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:369] Importing PsdImagePlugin
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:369] Importing SgiImagePlugin
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:369] Importing SpiderImagePlugin
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:369] Importing SunImagePlugin
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:369] Importing TgaImagePlugin
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:369] Importing TiffImagePlugin
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:369] Importing WebPImagePlugin
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:369] Importing WmfImagePlugin
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:369] Importing XbmImagePlugin
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:369] Importing XpmImagePlugin
[2022-12-05T02:41:10] DEBUG [PIL.Image.init:369] Importing XVThumbImagePlugin
[2022-12-05T02:41:33] DEBUG [PIL.PngImagePlugin.call:201] STREAM b'IHDR' 16 13
[2022-12-05T02:41:33] DEBUG [PIL.PngImagePlugin.call:201] STREAM b'sRGB' 41 1
[2022-12-05T02:41:33] DEBUG [PIL.PngImagePlugin.call:201] STREAM b'gAMA' 54 4
[2022-12-05T02:41:33] DEBUG [PIL.PngImagePlugin.call:201] STREAM b'IDAT' 70 65466
[2022-12-05T02:46:57] WARNING [django.request.log_response:241] Not Found: /favicon.ico
[2022-12-05T02:47:05] WARNING [django.request.log_response:241] Not Found: /favicon.ico
[2022-12-05T02:47:41] WARNING [django.request.log_response:241] Not Found: /favicon.ico
[2022-12-05T02:47:56] WARNING [django.request.log_response:241] Not Found: /favicon.ico
[2022-12-05T02:47:57] WARNING [django.request.log_response:241] Not Found: /favicon.ico
[2022-12-05T02:48:14] WARNING [django.request.log_response:241] Not Found: /favicon.ico
[2022-12-05T02:49:00] WARNING [django.request.log_response:241] Not Found: /favicon.ico
[2022-12-05T03:07:18] WARNING [django.request.log_response:241] Not Found: /favicon.ico
[2022-12-05T03:07:20] WARNING [django.request.log_response:241] Not Found: /favicon.ico
[2022-12-05T03:07:21] WARNING [django.request.log_response:241] Not Found: /favicon.ico
[2022-12-05T03:09:36] WARNING [django.request.log_response:241] Not Found: /favicon.ico
[2022-12-05T03:14:27] WARNING [django.request.log_response:241] Not Found: /favicon.ico
[2022-12-05T03:14:30] WARNING [django.request.log_response:241] Not Found: /favicon.ico
[2022-12-05T03:21:52] WARNING [django.request.log_response:241] Not Found: /favicon.ico
[2022-12-05T03:26:03] WARNING [django.request.log_response:241] Not Found: /favicon.ico
[2022-12-05T03:26:26] WARNING [django.request.log_response:241] Not Found: /favicon.ico
[2022-12-05T03:26:26] WARNING [django.request.log_response:241] Not Found: /favicon.ico
[2022-12-05T03:26:27] WARNING [django.request.log_response:241] Not Found: /favicon.ico
[2022-12-05T03:26:27] WARNING [django.request.log_response:241] Not Found: /favicon.ico
[2022-12-05T03:26:27] WARNING [django.request.log_response:241] Not Found: /favicon.ico
[2022-12-05T03:35:07] WARNING [django.request.log_response:241] Not Found: /favicon.ico
[2022-12-05T03:35:08] WARNING [django.request.log_response:241] Not Found: /favicon.ico
[2022-12-05T03:39:42] WARNING [django.request.log_response:241] Not Found: /favicon.ico
[2022-12-05T03:47:47] ERROR [django.request.log_response:241] Internal Server Error: /apps/instagram/appinfo/
Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\yash\billsnap\billsnapdec\dashboard\views.py", line 209, in appinfo
    plan = app.plan_set.all().filter(default_for_customer=True)[0]
  File "D:\yash\billsnap\env\lib\site-packages\django\db\models\query.py", line 446, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
[2022-12-05T03:48:00] ERROR [django.request.log_response:241] Internal Server Error: /apps/instagram/appinfo/
Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\yash\billsnap\billsnapdec\dashboard\views.py", line 209, in appinfo
    plan = app.plan_set.all().filter(default_for_customer=True)[0]
  File "D:\yash\billsnap\env\lib\site-packages\django\db\models\query.py", line 446, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
[2022-12-05T03:48:20] WARNING [django.request.log_response:241] Not Found: /css/searchicon.png
[2022-12-05T04:08:58] WARNING [django.request.log_response:241] Not Found: /favicon.ico
[2022-12-05T04:09:20] WARNING [django.request.log_response:241] Not Found: /favicon.ico
[2022-12-05T04:11:46] WARNING [django.request.log_response:241] Not Found: /favicon.ico
[2022-12-05T04:12:31] WARNING [django.request.log_response:241] Not Found: /favicon.ico
[2022-12-05T04:14:09] WARNING [django.request.log_response:241] Not Found: /favicon.ico
[2022-12-05T04:19:54] WARNING [django.request.log_response:241] Not Found: /favicon.ico
[2022-12-05T04:20:52] INFO [root.showapps:70] yaswanth_seen the whole applist
[2022-12-05T04:20:55] WARNING [django.request.log_response:241] Not Found: /css/searchicon.png
[2022-12-05T04:34:14] ERROR [django.request.log_response:241] Internal Server Error: /groups/group/55NKdEOBI9
Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\yash\billsnap\billsnapdec\groups\views.py", line 53, in show_group
    return render(request, 'groups-panel/group.html', payload)
  File "D:\yash\billsnap\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'groups-panel' with arguments '('',)' not found. 1 pattern(s) tried: ['groups/panel/(?P<slug>[^/]+)\\Z']
[2022-12-05T04:34:59] ERROR [django.request.log_response:241] Internal Server Error: /groups/group/55NKdEOBI9
Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\yash\billsnap\billsnapdec\groups\views.py", line 53, in show_group
    return render(request, 'groups-panel/group.html', payload)
  File "D:\yash\billsnap\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'groups-panel' with arguments '('',)' not found. 1 pattern(s) tried: ['groups/panel/(?P<slug>[^/]+)\\Z']
[2022-12-05T04:35:02] ERROR [django.request.log_response:241] Internal Server Error: /groups/group/55NKdEOBI9
Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\yash\billsnap\billsnapdec\groups\views.py", line 53, in show_group
    return render(request, 'groups-panel/group.html', payload)
  File "D:\yash\billsnap\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'groups-panel' with arguments '('',)' not found. 1 pattern(s) tried: ['groups/panel/(?P<slug>[^/]+)\\Z']
[2022-12-05T04:42:35] WARNING [django.request.log_response:241] Not Found: /favicon.ico
[2022-12-05T04:57:31] WARNING [django.request.log_response:241] Not Found: /favicon.ico
[2022-12-05T05:00:02] WARNING [django.request.log_response:241] Not Found: /favicon.ico
[2022-12-05T05:00:03] WARNING [django.request.log_response:241] Not Found: /favicon.ico
[2022-12-05T05:00:04] WARNING [django.request.log_response:241] Not Found: /favicon.ico
[2022-12-05T05:00:34] WARNING [django.request.log_response:241] Not Found: /favicon.ico
[2022-12-05T05:10:20] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\groups\forms.py changed, reloading.
[2022-12-05T05:10:39] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\groups\forms.py changed, reloading.
[2022-12-05T05:13:20] INFO [root.showapps:70] yaswanth_seen the whole applist
[2022-12-05T05:13:27] INFO [root.logout:189] yaswanth_ logged out
[2022-12-05T05:13:59] INFO [root.showapps:70] yaswanth_seen the whole applist
[2022-12-05T05:14:54] INFO [root.addapp:59] yaswanth_added an app
[2022-12-05T05:14:54] INFO [root.showapps:70] yaswanth_seen the whole applist
[2022-12-05T05:15:02] ERROR [django.request.log_response:241] Internal Server Error: /apps/darling/dashboard/
Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\yash\billsnap\billsnapdec\dashboard\views.py", line 204, in dashboard
    return render(request, 'dashboard.html', {'slug' : slug})
  File "D:\yash\billsnap\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\loader_tags.py", line 54, in render
    result = self.nodelist.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'update-profile' with arguments '('yaswanth',)' not found. 1 pattern(s) tried: ['account/(?P<slug>[^/]+)/edit/(?P<appslug>[^/]+)\\Z']
[2022-12-05T05:15:39] WARNING [django.request.log_response:241] Not Found: /apps/darling/dashboard/assets/img/ivancik.jpg
[2022-12-05T05:15:55] INFO [root.editapp:95] yaswanth_edited an app
[2022-12-05T05:16:04] WARNING [django.request.log_response:241] Not Found: /css/searchicon.png
[2022-12-05T05:23:24] ERROR [django.request.log_response:241] Internal Server Error: /plans/plan/tM9ViI223y/
Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\yash\billsnap\billsnapdec\plans\views.py", line 80, in show_plan
    return render(request, 'plans-panel/plan.html', payload)
  File "D:\yash\billsnap\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "D:\yash\billsnap\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\yash\billsnap\env\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'update-group' with arguments '('neha', '')' not found. 1 pattern(s) tried: ['groups/update\\-group/(?P<slug>[^/]+)/(?P<groupslug>[^/]+)\\Z']
[2022-12-05T05:30:48] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\plans\forms.py changed, reloading.
[2022-12-05T05:31:11] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\plans\forms.py changed, reloading.
[2022-12-05T05:31:18] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\plans\forms.py changed, reloading.
[2022-12-05T05:31:22] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\plans\forms.py changed, reloading.
[2022-12-05T05:39:37] INFO [root.showapps:70] yaswanth_seen the whole applist
[2022-12-05T05:39:44] WARNING [django.request.log_response:241] Not Found: /apps/jin/dashboard/assets/img/ivancik.jpg
[2022-12-05T05:40:02] ERROR [django.request.log_response:241] Internal Server Error: /apps/jin/bulkupload/
Traceback (most recent call last):
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\yash\billsnap\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\yash\billsnap\billsnapdec\dashboard\views.py", line 172, in bulk_upload
    df=pd.read_csv(csvfile)
  File "D:\yash\billsnap\env\lib\site-packages\pandas\util\_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "D:\yash\billsnap\env\lib\site-packages\pandas\io\parsers\readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "D:\yash\billsnap\env\lib\site-packages\pandas\io\parsers\readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "D:\yash\billsnap\env\lib\site-packages\pandas\io\parsers\readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "D:\yash\billsnap\env\lib\site-packages\pandas\io\parsers\readers.py", line 1753, in _make_engine
    return mapping[engine](f, **self.options)
  File "D:\yash\billsnap\env\lib\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 79, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas\_libs\parsers.pyx", line 547, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas\_libs\parsers.pyx", line 664, in pandas._libs.parsers.TextReader._get_header
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
[2022-12-05T05:43:18] WARNING [django.request.log_response:241] Not Found: /css/searchicon.png
[2022-12-05T05:50:56] INFO [root.update_profile:284] yaswanth_ updated profile
[2022-12-05T05:51:38] INFO [django.utils.autoreload.trigger_reload:266] D:\yash\billsnap\billsnapdec\dashboard\urls.py changed, reloading.
[2022-12-05T05:52:31] INFO [root.showapps:70] yaswanth_seen the whole applist
[2022-12-05T05:52:38] WARNING [django.request.log_response:241] Not Found: /apps/darling/dashboard/assets/img/ivancik.jpg
[2022-12-05T00:40:00] WARNING [django.request.log_response:241] Not Found: /favicon.ico
[2022-12-05T00:40:12] INFO [root.showapps:70] yaswanth_seen the whole applist
[2022-12-05T00:40:16] WARNING [django.request.log_response:241] Not Found: /apps/jin/dashboard/assets/img/ivancik.jpg
